name: Go get update

on:
  schedule:
    - cron: "58 8 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  go-mod-tidy:
    name: go get update

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go get update
        run: go get -u

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push to branch
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_author: github_actions
          message: Automated go get update
          new_branch: update/go-mod-tidy
          push: origin update/go-mod-tidy --set-upstream --force

      - name: Create pull request
        if: env.changes == 'true'
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          label: tidy
          title: Automated go get update
          get_diff: true
